name: DIVAHisDB_tools
channels:
  - defaults
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - matplotlib
  - numpy
  - pillow
  - python=3.7.3
  - torchvision
  - tqdm
  - pip:
    - fire==0.3.1
